"""
These enums are defined in ``wgpu.enums``, but are also available from the root wgpu namespace.

Enums are choices; exactly one field must be selected.
Enum values are strings, so instead of ``wgpu.TextureFormat.rgba8unorm``,
one can also write ``"rgba8unorm"``.
"""

from ._coreutils import BaseEnum as _BaseEnum


class Enum(_BaseEnum):
    """Base enum class for wgpu."""

    pass


# CODE BELOW THIS POINT IS AUTOGENERATED - DO NOT EDIT


# There are 33 enums

__all__ = [
    "PowerPreference",
    "FeatureName",
    "BufferMapState",
    "TextureDimension",
    "TextureViewDimension",
    "TextureAspect",
    "TextureFormat",
    "AddressMode",
    "FilterMode",
    "MipmapFilterMode",
    "CompareFunction",
    "BufferBindingType",
    "SamplerBindingType",
    "TextureSampleType",
    "StorageTextureAccess",
    "CompilationMessageType",
    "PipelineErrorReason",
    "AutoLayoutMode",
    "PrimitiveTopology",
    "FrontFace",
    "CullMode",
    "BlendFactor",
    "BlendOperation",
    "StencilOperation",
    "IndexFormat",
    "VertexFormat",
    "VertexStepMode",
    "LoadOp",
    "StoreOp",
    "QueryType",
    "CanvasAlphaMode",
    "DeviceLostReason",
    "ErrorFilter",
]


class PowerPreference(Enum):

    low_power = None
    high_performance = None


class FeatureName(Enum):

    depth_clip_control = None
    depth32float_stencil8 = None
    texture_compression_bc = None
    texture_compression_etc2 = None
    texture_compression_astc = None
    timestamp_query = None
    indirect_first_instance = None
    shader_f16 = None
    rg11b10ufloat_renderable = None
    bgra8unorm_storage = None
    float32_filterable = None
    clip_distances = None


class BufferMapState(Enum):

    unmapped = None
    pending = None
    mapped = None


class TextureDimension(Enum):

    d1 = None
    d2 = None
    d3 = None


class TextureViewDimension(Enum):

    d1 = None
    d2 = None
    d2_array = None
    cube = None
    cube_array = None
    d3 = None


class TextureAspect(Enum):

    all = None
    stencil_only = None
    depth_only = None


class TextureFormat(Enum):

    r8unorm = None
    r8snorm = None
    r8uint = None
    r8sint = None
    r16uint = None
    r16sint = None
    r16float = None
    rg8unorm = None
    rg8snorm = None
    rg8uint = None
    rg8sint = None
    r32uint = None
    r32sint = None
    r32float = None
    rg16uint = None
    rg16sint = None
    rg16float = None
    rgba8unorm = None
    rgba8unorm_srgb = None
    rgba8snorm = None
    rgba8uint = None
    rgba8sint = None
    bgra8unorm = None
    bgra8unorm_srgb = None
    rgb9e5ufloat = None
    rgb10a2uint = None
    rgb10a2unorm = None
    rg11b10ufloat = None
    rg32uint = None
    rg32sint = None
    rg32float = None
    rgba16uint = None
    rgba16sint = None
    rgba16float = None
    rgba32uint = None
    rgba32sint = None
    rgba32float = None
    stencil8 = None
    depth16unorm = None
    depth24plus = None
    depth24plus_stencil8 = None
    depth32float = None
    depth32float_stencil8 = None
    bc1_rgba_unorm = None
    bc1_rgba_unorm_srgb = None
    bc2_rgba_unorm = None
    bc2_rgba_unorm_srgb = None
    bc3_rgba_unorm = None
    bc3_rgba_unorm_srgb = None
    bc4_r_unorm = None
    bc4_r_snorm = None
    bc5_rg_unorm = None
    bc5_rg_snorm = None
    bc6h_rgb_ufloat = None
    bc6h_rgb_float = None
    bc7_rgba_unorm = None
    bc7_rgba_unorm_srgb = None
    etc2_rgb8unorm = None
    etc2_rgb8unorm_srgb = None
    etc2_rgb8a1unorm = None
    etc2_rgb8a1unorm_srgb = None
    etc2_rgba8unorm = None
    etc2_rgba8unorm_srgb = None
    eac_r11unorm = None
    eac_r11snorm = None
    eac_rg11unorm = None
    eac_rg11snorm = None
    astc_4x4_unorm = None
    astc_4x4_unorm_srgb = None
    astc_5x4_unorm = None
    astc_5x4_unorm_srgb = None
    astc_5x5_unorm = None
    astc_5x5_unorm_srgb = None
    astc_6x5_unorm = None
    astc_6x5_unorm_srgb = None
    astc_6x6_unorm = None
    astc_6x6_unorm_srgb = None
    astc_8x5_unorm = None
    astc_8x5_unorm_srgb = None
    astc_8x6_unorm = None
    astc_8x6_unorm_srgb = None
    astc_8x8_unorm = None
    astc_8x8_unorm_srgb = None
    astc_10x5_unorm = None
    astc_10x5_unorm_srgb = None
    astc_10x6_unorm = None
    astc_10x6_unorm_srgb = None
    astc_10x8_unorm = None
    astc_10x8_unorm_srgb = None
    astc_10x10_unorm = None
    astc_10x10_unorm_srgb = None
    astc_12x10_unorm = None
    astc_12x10_unorm_srgb = None
    astc_12x12_unorm = None
    astc_12x12_unorm_srgb = None


class AddressMode(Enum):

    clamp_to_edge = None
    repeat = None
    mirror_repeat = None


class FilterMode(Enum):

    nearest = None
    linear = None


class MipmapFilterMode(Enum):

    nearest = None
    linear = None


class CompareFunction(Enum):

    never = None
    less = None
    equal = None
    less_equal = None
    greater = None
    not_equal = None
    greater_equal = None
    always = None


class BufferBindingType(Enum):

    uniform = None
    storage = None
    read_only_storage = None


class SamplerBindingType(Enum):

    filtering = None
    non_filtering = None
    comparison = None


class TextureSampleType(Enum):

    float = None
    unfilterable_float = None
    depth = None
    sint = None
    uint = None


class StorageTextureAccess(Enum):

    write_only = None
    read_only = None
    read_write = None


class CompilationMessageType(Enum):

    error = None
    warning = None
    info = None


class PipelineErrorReason(Enum):

    validation = None
    internal = None


class AutoLayoutMode(Enum):

    auto = None


class PrimitiveTopology(Enum):

    point_list = None
    line_list = None
    line_strip = None
    triangle_list = None
    triangle_strip = None


class FrontFace(Enum):

    ccw = None
    cw = None


class CullMode(Enum):

    none = None
    front = None
    back = None


class BlendFactor(Enum):

    zero = None
    one = None
    src = None
    one_minus_src = None
    src_alpha = None
    one_minus_src_alpha = None
    dst = None
    one_minus_dst = None
    dst_alpha = None
    one_minus_dst_alpha = None
    src_alpha_saturated = None
    constant = None
    one_minus_constant = None


class BlendOperation(Enum):

    add = None
    subtract = None
    reverse_subtract = None
    min = None
    max = None


class StencilOperation(Enum):

    keep = None
    zero = None
    replace = None
    invert = None
    increment_clamp = None
    decrement_clamp = None
    increment_wrap = None
    decrement_wrap = None


class IndexFormat(Enum):

    uint16 = None
    uint32 = None


class VertexFormat(Enum):

    uint8x2 = None
    uint8x4 = None
    sint8x2 = None
    sint8x4 = None
    unorm8x2 = None
    unorm8x4 = None
    snorm8x2 = None
    snorm8x4 = None
    uint16x2 = None
    uint16x4 = None
    sint16x2 = None
    sint16x4 = None
    unorm16x2 = None
    unorm16x4 = None
    snorm16x2 = None
    snorm16x4 = None
    float16x2 = None
    float16x4 = None
    float32 = None
    float32x2 = None
    float32x3 = None
    float32x4 = None
    uint32 = None
    uint32x2 = None
    uint32x3 = None
    uint32x4 = None
    sint32 = None
    sint32x2 = None
    sint32x3 = None
    sint32x4 = None
    unorm10_10_10_2 = None


class VertexStepMode(Enum):

    vertex = None
    instance = None


class LoadOp(Enum):

    load = None
    clear = None


class StoreOp(Enum):

    store = None
    discard = None


class QueryType(Enum):

    occlusion = None
    timestamp = None


class CanvasAlphaMode(Enum):

    opaque = None
    premultiplied = None


class DeviceLostReason(Enum):

    unknown = None
    destroyed = None


class ErrorFilter(Enum):

    validation = None
    out_of_memory = None
    internal = None
