"""
These structs are defined in ``wgpu.structs``, but are also available from the root wgpu namespace.

The classes below are dataclasses; they are used for typing, (static and
dynamic) autocompletion, and docs. The recommended way to use wgpu structs is to
instantiate these classes, since that results in a code that is readable
and type-checkable. However, structs can also be defined using plain Python
dicts. Their fields are checked at runtime.
"""

# Allow using class names in type annotations, without Ruff triggering F821
from __future__ import annotations

from dataclasses import dataclass
from collections.abc import Mapping
from typing import Sequence, Optional

from ._coreutils import ArrayLike, CanvasLike
from . import _classes as classes
from . import flags
from . import enums


class Struct(Mapping):
    # By inherting from Mapping, these structs can be used as kwargs, e.g. ``some_method(**struct)``.

    def __repr__(self):
        return self._repr()

    def _repr(self, indent=""):
        new_indent = indent + "    "
        lines = [f"wgpu.{self.__class__.__name__}("]
        for name, type in self.__annotations__.items():
            if type.startswith(("flags.", "enums.")):
                type = type.split(".")[-1]
            val = self[name]
            if isinstance(val, Struct):
                valr = val._repr(new_indent)
            else:
                valr = repr(val)
            lines.append(f"{new_indent}{name}: {type} = {valr}")
        lines.append(f"{indent})")
        return "\n".join(lines)

    def __getitem__(self, key):
        return self.__dict__[key]

    def __iter__(self):
        return iter(self.__dict__)

    def __len__(self):
        return len(self.__dict__)

    def get(self, key, default=None):
        """Get method that returns the default when the acual value is None."""
        # Get the stored value. Note that we don't allow unknown/invalid keys
        val = self.__dict__[key]
        # None means default
        if val is None:
            return default
        return val


# CODE BELOW THIS POINT IS AUTOGENERATED - DO NOT EDIT


# There are 60 structs

__all__ = [
    "BindGroupDescriptor",
    "BindGroupEntry",
    "BindGroupLayoutDescriptor",
    "BindGroupLayoutEntry",
    "BlendComponent",
    "BlendState",
    "BufferBinding",
    "BufferBindingLayout",
    "BufferDescriptor",
    "CanvasConfiguration",
    "CanvasToneMapping",
    "Color",
    "ColorTargetState",
    "CommandBufferDescriptor",
    "CommandEncoderDescriptor",
    "ComputePassDescriptor",
    "ComputePassTimestampWrites",
    "ComputePipelineDescriptor",
    "CopyExternalImageDestInfo",
    "CopyExternalImageSourceInfo",
    "DepthStencilState",
    "DeviceDescriptor",
    "Extent3D",
    "ExternalTextureBindingLayout",
    "ExternalTextureDescriptor",
    "FragmentState",
    "MultisampleState",
    "Origin2D",
    "Origin3D",
    "PipelineErrorInit",
    "PipelineLayoutDescriptor",
    "PrimitiveState",
    "ProgrammableStage",
    "QuerySetDescriptor",
    "QueueDescriptor",
    "RenderBundleDescriptor",
    "RenderBundleEncoderDescriptor",
    "RenderPassColorAttachment",
    "RenderPassDepthStencilAttachment",
    "RenderPassDescriptor",
    "RenderPassLayout",
    "RenderPassTimestampWrites",
    "RenderPipelineDescriptor",
    "RequestAdapterOptions",
    "SamplerBindingLayout",
    "SamplerDescriptor",
    "ShaderModuleCompilationHint",
    "ShaderModuleDescriptor",
    "StencilFaceState",
    "StorageTextureBindingLayout",
    "TexelCopyBufferInfo",
    "TexelCopyBufferLayout",
    "TexelCopyTextureInfo",
    "TextureBindingLayout",
    "TextureDescriptor",
    "TextureViewDescriptor",
    "UncapturedErrorEventInit",
    "VertexAttribute",
    "VertexBufferLayout",
    "VertexState",
]


@dataclass(kw_only=True, repr=False)
class RequestAdapterOptions(Struct):
    #:
    feature_level: Optional[str] = "core"
    #: :obj:`enums.PowerPreference <wgpu.enums.PowerPreference>`
    power_preference: Optional[enums.PowerPreferenceEnum]
    #:
    force_fallback_adapter: Optional[bool] = False
    #:
    xr_compatible: Optional[bool] = False


RequestAdapterOptionsStruct = RequestAdapterOptions | dict


@dataclass(kw_only=True, repr=False)
class DeviceDescriptor(Struct):
    #:
    label: Optional[str] = ""
    #: list[:obj:`enums.FeatureName <wgpu.enums.FeatureName>`]
    required_features: Optional[Sequence[enums.FeatureNameEnum]] = ()
    #:
    required_limits: Optional[dict[str, int | None] | None] = None
    #:
    default_queue: Optional[QueueDescriptorStruct | None] = None


DeviceDescriptorStruct = DeviceDescriptor | dict


@dataclass(kw_only=True, repr=False)
class BufferDescriptor(Struct):
    #:
    label: Optional[str] = ""
    #:
    size: int
    #: :obj:`flags.BufferUsage <wgpu.flags.BufferUsage>`
    usage: flags.BufferUsageFlags
    #:
    mapped_at_creation: Optional[bool] = False


BufferDescriptorStruct = BufferDescriptor | dict


@dataclass(kw_only=True, repr=False)
class TextureDescriptor(Struct):
    #:
    label: Optional[str] = ""
    #:
    size: tuple[int, int, int] | Extent3DStruct
    #:
    mip_level_count: Optional[int] = 1
    #:
    sample_count: Optional[int] = 1
    #: :obj:`enums.TextureDimension <wgpu.enums.TextureDimension>`
    dimension: Optional[enums.TextureDimensionEnum] = "2d"
    #: :obj:`enums.TextureFormat <wgpu.enums.TextureFormat>`
    format: enums.TextureFormatEnum
    #: :obj:`flags.TextureUsage <wgpu.flags.TextureUsage>`
    usage: flags.TextureUsageFlags
    #: list[:obj:`enums.TextureFormat <wgpu.enums.TextureFormat>`]
    view_formats: Optional[Sequence[enums.TextureFormatEnum]] = ()


TextureDescriptorStruct = TextureDescriptor | dict


@dataclass(kw_only=True, repr=False)
class TextureViewDescriptor(Struct):
    #:
    label: Optional[str] = ""
    #: :obj:`enums.TextureFormat <wgpu.enums.TextureFormat>`
    format: Optional[enums.TextureFormatEnum]
    #: :obj:`enums.TextureViewDimension <wgpu.enums.TextureViewDimension>`
    dimension: Optional[enums.TextureViewDimensionEnum]
    #: :obj:`flags.TextureUsage <wgpu.flags.TextureUsage>`
    usage: Optional[flags.TextureUsageFlags] = 0
    #: :obj:`enums.TextureAspect <wgpu.enums.TextureAspect>`
    aspect: Optional[enums.TextureAspectEnum] = "all"
    #:
    base_mip_level: Optional[int] = 0
    #:
    mip_level_count: Optional[int]
    #:
    base_array_layer: Optional[int] = 0
    #:
    array_layer_count: Optional[int]


TextureViewDescriptorStruct = TextureViewDescriptor | dict


@dataclass(kw_only=True, repr=False)
class ExternalTextureDescriptor(Struct):
    #:
    label: Optional[str] = ""
    #:
    source: ArrayLike | object
    #:
    color_space: Optional[str] = "srgb"


ExternalTextureDescriptorStruct = ExternalTextureDescriptor | dict


@dataclass(kw_only=True, repr=False)
class SamplerDescriptor(Struct):
    #:
    label: Optional[str] = ""
    #: :obj:`enums.AddressMode <wgpu.enums.AddressMode>`
    address_mode_u: Optional[enums.AddressModeEnum] = "clamp-to-edge"
    #: :obj:`enums.AddressMode <wgpu.enums.AddressMode>`
    address_mode_v: Optional[enums.AddressModeEnum] = "clamp-to-edge"
    #: :obj:`enums.AddressMode <wgpu.enums.AddressMode>`
    address_mode_w: Optional[enums.AddressModeEnum] = "clamp-to-edge"
    #: :obj:`enums.FilterMode <wgpu.enums.FilterMode>`
    mag_filter: Optional[enums.FilterModeEnum] = "nearest"
    #: :obj:`enums.FilterMode <wgpu.enums.FilterMode>`
    min_filter: Optional[enums.FilterModeEnum] = "nearest"
    #: :obj:`enums.MipmapFilterMode <wgpu.enums.MipmapFilterMode>`
    mipmap_filter: Optional[enums.MipmapFilterModeEnum] = "nearest"
    #:
    lod_min_clamp: Optional[float] = 0
    #:
    lod_max_clamp: Optional[float] = 32
    #: :obj:`enums.CompareFunction <wgpu.enums.CompareFunction>`
    compare: Optional[enums.CompareFunctionEnum]
    #:
    max_anisotropy: Optional[int] = 1


SamplerDescriptorStruct = SamplerDescriptor | dict


@dataclass(kw_only=True, repr=False)
class BindGroupLayoutDescriptor(Struct):
    #:
    label: Optional[str] = ""
    #:
    entries: Sequence[BindGroupLayoutEntryStruct]


BindGroupLayoutDescriptorStruct = BindGroupLayoutDescriptor | dict


@dataclass(kw_only=True, repr=False)
class BindGroupLayoutEntry(Struct):
    #:
    binding: int
    #: :obj:`flags.ShaderStage <wgpu.flags.ShaderStage>`
    visibility: flags.ShaderStageFlags
    #:
    buffer: Optional[BufferBindingLayoutStruct]
    #:
    sampler: Optional[SamplerBindingLayoutStruct]
    #:
    texture: Optional[TextureBindingLayoutStruct]
    #:
    storage_texture: Optional[StorageTextureBindingLayoutStruct]
    #:
    external_texture: Optional[ExternalTextureBindingLayoutStruct]


BindGroupLayoutEntryStruct = BindGroupLayoutEntry | dict


@dataclass(kw_only=True, repr=False)
class BufferBindingLayout(Struct):
    #: :obj:`enums.BufferBindingType <wgpu.enums.BufferBindingType>`
    type: Optional[enums.BufferBindingTypeEnum] = "uniform"
    #:
    has_dynamic_offset: Optional[bool] = False
    #:
    min_binding_size: Optional[int] = 0


BufferBindingLayoutStruct = BufferBindingLayout | dict


@dataclass(kw_only=True, repr=False)
class SamplerBindingLayout(Struct):
    #: :obj:`enums.SamplerBindingType <wgpu.enums.SamplerBindingType>`
    type: Optional[enums.SamplerBindingTypeEnum] = "filtering"


SamplerBindingLayoutStruct = SamplerBindingLayout | dict


@dataclass(kw_only=True, repr=False)
class TextureBindingLayout(Struct):
    #: :obj:`enums.TextureSampleType <wgpu.enums.TextureSampleType>`
    sample_type: Optional[enums.TextureSampleTypeEnum] = "float"
    #: :obj:`enums.TextureViewDimension <wgpu.enums.TextureViewDimension>`
    view_dimension: Optional[enums.TextureViewDimensionEnum] = "2d"
    #:
    multisampled: Optional[bool] = False


TextureBindingLayoutStruct = TextureBindingLayout | dict


@dataclass(kw_only=True, repr=False)
class StorageTextureBindingLayout(Struct):
    #: :obj:`enums.StorageTextureAccess <wgpu.enums.StorageTextureAccess>`
    access: Optional[enums.StorageTextureAccessEnum] = "write-only"
    #: :obj:`enums.TextureFormat <wgpu.enums.TextureFormat>`
    format: enums.TextureFormatEnum
    #: :obj:`enums.TextureViewDimension <wgpu.enums.TextureViewDimension>`
    view_dimension: Optional[enums.TextureViewDimensionEnum] = "2d"


StorageTextureBindingLayoutStruct = StorageTextureBindingLayout | dict


@dataclass(kw_only=True, repr=False)
class ExternalTextureBindingLayout(Struct):
    pass


ExternalTextureBindingLayoutStruct = ExternalTextureBindingLayout | dict


@dataclass(kw_only=True, repr=False)
class BindGroupDescriptor(Struct):
    #:
    label: Optional[str] = ""
    #:
    layout: classes.GPUBindGroupLayout
    #:
    entries: Sequence[BindGroupEntryStruct]


BindGroupDescriptorStruct = BindGroupDescriptor | dict


@dataclass(kw_only=True, repr=False)
class BindGroupEntry(Struct):
    #:
    binding: int
    #:
    resource: (
        classes.GPUBuffer
        | classes.GPUSampler
        | classes.GPUTexture
        | classes.GPUTextureView
        | object
        | BufferBindingStruct
    )


BindGroupEntryStruct = BindGroupEntry | dict


@dataclass(kw_only=True, repr=False)
class BufferBinding(Struct):
    #:
    buffer: classes.GPUBuffer
    #:
    offset: Optional[int] = 0
    #:
    size: Optional[int]


BufferBindingStruct = BufferBinding | dict


@dataclass(kw_only=True, repr=False)
class PipelineLayoutDescriptor(Struct):
    #:
    label: Optional[str] = ""
    #:
    bind_group_layouts: Sequence[classes.GPUBindGroupLayout]


PipelineLayoutDescriptorStruct = PipelineLayoutDescriptor | dict


@dataclass(kw_only=True, repr=False)
class ShaderModuleDescriptor(Struct):
    #:
    label: Optional[str] = ""
    #:
    code: str
    #:
    compilation_hints: Optional[Sequence[ShaderModuleCompilationHintStruct]] = ()


ShaderModuleDescriptorStruct = ShaderModuleDescriptor | dict


@dataclass(kw_only=True, repr=False)
class ShaderModuleCompilationHint(Struct):
    #:
    entry_point: str
    #: :class:`GPUPipelineLayout <wgpu.GPUPipelineLayout>` | :obj:`enums.AutoLayoutMode <wgpu.enums.AutoLayoutMode>`
    layout: Optional[classes.GPUPipelineLayout | enums.AutoLayoutModeEnum]


ShaderModuleCompilationHintStruct = ShaderModuleCompilationHint | dict


@dataclass(kw_only=True, repr=False)
class PipelineErrorInit(Struct):
    #: :obj:`enums.PipelineErrorReason <wgpu.enums.PipelineErrorReason>`
    reason: enums.PipelineErrorReasonEnum


PipelineErrorInitStruct = PipelineErrorInit | dict


@dataclass(kw_only=True, repr=False)
class ProgrammableStage(Struct):
    #:
    module: classes.GPUShaderModule
    #:
    entry_point: Optional[str]
    #:
    constants: Optional[dict[str, float] | None] = None


ProgrammableStageStruct = ProgrammableStage | dict


@dataclass(kw_only=True, repr=False)
class ComputePipelineDescriptor(Struct):
    #:
    label: Optional[str] = ""
    #: :class:`GPUPipelineLayout <wgpu.GPUPipelineLayout>` | :obj:`enums.AutoLayoutMode <wgpu.enums.AutoLayoutMode>`
    layout: classes.GPUPipelineLayout | enums.AutoLayoutModeEnum
    #:
    compute: ProgrammableStageStruct


ComputePipelineDescriptorStruct = ComputePipelineDescriptor | dict


@dataclass(kw_only=True, repr=False)
class RenderPipelineDescriptor(Struct):
    #:
    label: Optional[str] = ""
    #: :class:`GPUPipelineLayout <wgpu.GPUPipelineLayout>` | :obj:`enums.AutoLayoutMode <wgpu.enums.AutoLayoutMode>`
    layout: classes.GPUPipelineLayout | enums.AutoLayoutModeEnum
    #:
    vertex: VertexStateStruct
    #:
    primitive: Optional[PrimitiveStateStruct | None] = None
    #:
    depth_stencil: Optional[DepthStencilStateStruct]
    #:
    multisample: Optional[MultisampleStateStruct | None] = None
    #:
    fragment: Optional[FragmentStateStruct]


RenderPipelineDescriptorStruct = RenderPipelineDescriptor | dict


@dataclass(kw_only=True, repr=False)
class PrimitiveState(Struct):
    #: :obj:`enums.PrimitiveTopology <wgpu.enums.PrimitiveTopology>`
    topology: Optional[enums.PrimitiveTopologyEnum] = "triangle-list"
    #: :obj:`enums.IndexFormat <wgpu.enums.IndexFormat>`
    strip_index_format: Optional[enums.IndexFormatEnum]
    #: :obj:`enums.FrontFace <wgpu.enums.FrontFace>`
    front_face: Optional[enums.FrontFaceEnum] = "ccw"
    #: :obj:`enums.CullMode <wgpu.enums.CullMode>`
    cull_mode: Optional[enums.CullModeEnum] = "none"
    #:
    unclipped_depth: Optional[bool] = False


PrimitiveStateStruct = PrimitiveState | dict


@dataclass(kw_only=True, repr=False)
class MultisampleState(Struct):
    #:
    count: Optional[int] = 1
    #:
    mask: Optional[int] = 0xFFFFFFFF
    #:
    alpha_to_coverage_enabled: Optional[bool] = False


MultisampleStateStruct = MultisampleState | dict


@dataclass(kw_only=True, repr=False)
class FragmentState(Struct):
    #:
    module: classes.GPUShaderModule
    #:
    entry_point: Optional[str]
    #:
    constants: Optional[dict[str, float] | None] = None
    #:
    targets: Sequence[ColorTargetStateStruct]


FragmentStateStruct = FragmentState | dict


@dataclass(kw_only=True, repr=False)
class ColorTargetState(Struct):
    #: :obj:`enums.TextureFormat <wgpu.enums.TextureFormat>`
    format: enums.TextureFormatEnum
    #:
    blend: Optional[BlendStateStruct]
    #: :obj:`flags.ColorWrite <wgpu.flags.ColorWrite>`
    write_mask: Optional[flags.ColorWriteFlags] = 0xF


ColorTargetStateStruct = ColorTargetState | dict


@dataclass(kw_only=True, repr=False)
class BlendState(Struct):
    #:
    color: BlendComponentStruct
    #:
    alpha: BlendComponentStruct


BlendStateStruct = BlendState | dict


@dataclass(kw_only=True, repr=False)
class BlendComponent(Struct):
    #: :obj:`enums.BlendOperation <wgpu.enums.BlendOperation>`
    operation: Optional[enums.BlendOperationEnum] = "add"
    #: :obj:`enums.BlendFactor <wgpu.enums.BlendFactor>`
    src_factor: Optional[enums.BlendFactorEnum] = "one"
    #: :obj:`enums.BlendFactor <wgpu.enums.BlendFactor>`
    dst_factor: Optional[enums.BlendFactorEnum] = "zero"


BlendComponentStruct = BlendComponent | dict


@dataclass(kw_only=True, repr=False)
class DepthStencilState(Struct):
    #: :obj:`enums.TextureFormat <wgpu.enums.TextureFormat>`
    format: enums.TextureFormatEnum
    #:
    depth_write_enabled: Optional[bool]
    #: :obj:`enums.CompareFunction <wgpu.enums.CompareFunction>`
    depth_compare: Optional[enums.CompareFunctionEnum]
    #:
    stencil_front: Optional[StencilFaceStateStruct | None] = None
    #:
    stencil_back: Optional[StencilFaceStateStruct | None] = None
    #:
    stencil_read_mask: Optional[int] = 0xFFFFFFFF
    #:
    stencil_write_mask: Optional[int] = 0xFFFFFFFF
    #:
    depth_bias: Optional[int] = 0
    #:
    depth_bias_slope_scale: Optional[float] = 0
    #:
    depth_bias_clamp: Optional[float] = 0


DepthStencilStateStruct = DepthStencilState | dict


@dataclass(kw_only=True, repr=False)
class StencilFaceState(Struct):
    #: :obj:`enums.CompareFunction <wgpu.enums.CompareFunction>`
    compare: Optional[enums.CompareFunctionEnum] = "always"
    #: :obj:`enums.StencilOperation <wgpu.enums.StencilOperation>`
    fail_op: Optional[enums.StencilOperationEnum] = "keep"
    #: :obj:`enums.StencilOperation <wgpu.enums.StencilOperation>`
    depth_fail_op: Optional[enums.StencilOperationEnum] = "keep"
    #: :obj:`enums.StencilOperation <wgpu.enums.StencilOperation>`
    pass_op: Optional[enums.StencilOperationEnum] = "keep"


StencilFaceStateStruct = StencilFaceState | dict


@dataclass(kw_only=True, repr=False)
class VertexState(Struct):
    #:
    module: classes.GPUShaderModule
    #:
    entry_point: Optional[str]
    #:
    constants: Optional[dict[str, float] | None] = None
    #:
    buffers: Optional[Sequence[VertexBufferLayoutStruct]] = ()


VertexStateStruct = VertexState | dict


@dataclass(kw_only=True, repr=False)
class VertexBufferLayout(Struct):
    #:
    array_stride: int
    #: :obj:`enums.VertexStepMode <wgpu.enums.VertexStepMode>`
    step_mode: Optional[enums.VertexStepModeEnum] = "vertex"
    #:
    attributes: Sequence[VertexAttributeStruct]


VertexBufferLayoutStruct = VertexBufferLayout | dict


@dataclass(kw_only=True, repr=False)
class VertexAttribute(Struct):
    #: :obj:`enums.VertexFormat <wgpu.enums.VertexFormat>`
    format: enums.VertexFormatEnum
    #:
    offset: int
    #:
    shader_location: int


VertexAttributeStruct = VertexAttribute | dict


@dataclass(kw_only=True, repr=False)
class TexelCopyBufferLayout(Struct):
    #:
    offset: Optional[int] = 0
    #:
    bytes_per_row: Optional[int]
    #:
    rows_per_image: Optional[int]


TexelCopyBufferLayoutStruct = TexelCopyBufferLayout | dict


@dataclass(kw_only=True, repr=False)
class TexelCopyBufferInfo(Struct):
    #:
    offset: Optional[int] = 0
    #:
    bytes_per_row: Optional[int]
    #:
    rows_per_image: Optional[int]
    #:
    buffer: classes.GPUBuffer


TexelCopyBufferInfoStruct = TexelCopyBufferInfo | dict


@dataclass(kw_only=True, repr=False)
class TexelCopyTextureInfo(Struct):
    #:
    texture: classes.GPUTexture
    #:
    mip_level: Optional[int] = 0
    #:
    origin: Optional[tuple[int, int, int] | Origin3DStruct | None] = None
    #: :obj:`enums.TextureAspect <wgpu.enums.TextureAspect>`
    aspect: Optional[enums.TextureAspectEnum] = "all"


TexelCopyTextureInfoStruct = TexelCopyTextureInfo | dict


@dataclass(kw_only=True, repr=False)
class CopyExternalImageDestInfo(Struct):
    #:
    texture: classes.GPUTexture
    #:
    mip_level: Optional[int] = 0
    #:
    origin: Optional[tuple[int, int, int] | Origin3DStruct | None] = None
    #: :obj:`enums.TextureAspect <wgpu.enums.TextureAspect>`
    aspect: Optional[enums.TextureAspectEnum] = "all"
    #:
    color_space: Optional[str] = "srgb"
    #:
    premultiplied_alpha: Optional[bool] = False


CopyExternalImageDestInfoStruct = CopyExternalImageDestInfo | dict


@dataclass(kw_only=True, repr=False)
class CopyExternalImageSourceInfo(Struct):
    #:
    source: ArrayLike | CanvasLike | object
    #:
    origin: Optional[tuple[int, int] | Origin2DStruct | None] = None
    #:
    flip_y: Optional[bool] = False


CopyExternalImageSourceInfoStruct = CopyExternalImageSourceInfo | dict


@dataclass(kw_only=True, repr=False)
class CommandBufferDescriptor(Struct):
    #:
    label: Optional[str] = ""


CommandBufferDescriptorStruct = CommandBufferDescriptor | dict


@dataclass(kw_only=True, repr=False)
class CommandEncoderDescriptor(Struct):
    #:
    label: Optional[str] = ""


CommandEncoderDescriptorStruct = CommandEncoderDescriptor | dict


@dataclass(kw_only=True, repr=False)
class ComputePassTimestampWrites(Struct):
    #:
    query_set: classes.GPUQuerySet
    #:
    beginning_of_pass_write_index: Optional[int]
    #:
    end_of_pass_write_index: Optional[int]


ComputePassTimestampWritesStruct = ComputePassTimestampWrites | dict


@dataclass(kw_only=True, repr=False)
class ComputePassDescriptor(Struct):
    #:
    label: Optional[str] = ""
    #:
    timestamp_writes: Optional[ComputePassTimestampWritesStruct]


ComputePassDescriptorStruct = ComputePassDescriptor | dict


@dataclass(kw_only=True, repr=False)
class RenderPassTimestampWrites(Struct):
    #:
    query_set: classes.GPUQuerySet
    #:
    beginning_of_pass_write_index: Optional[int]
    #:
    end_of_pass_write_index: Optional[int]


RenderPassTimestampWritesStruct = RenderPassTimestampWrites | dict


@dataclass(kw_only=True, repr=False)
class RenderPassDescriptor(Struct):
    #:
    label: Optional[str] = ""
    #:
    color_attachments: Sequence[RenderPassColorAttachmentStruct]
    #:
    depth_stencil_attachment: Optional[RenderPassDepthStencilAttachmentStruct]
    #:
    occlusion_query_set: Optional[classes.GPUQuerySet]
    #:
    timestamp_writes: Optional[RenderPassTimestampWritesStruct]
    #:
    max_draw_count: Optional[int] = 50000000


RenderPassDescriptorStruct = RenderPassDescriptor | dict


@dataclass(kw_only=True, repr=False)
class RenderPassColorAttachment(Struct):
    #:
    view: classes.GPUTexture | classes.GPUTextureView
    #:
    depth_slice: Optional[int]
    #:
    resolve_target: Optional[classes.GPUTexture | classes.GPUTextureView]
    #:
    clear_value: Optional[tuple[float, float, float, float] | ColorStruct]
    #: :obj:`enums.LoadOp <wgpu.enums.LoadOp>`
    load_op: enums.LoadOpEnum
    #: :obj:`enums.StoreOp <wgpu.enums.StoreOp>`
    store_op: enums.StoreOpEnum


RenderPassColorAttachmentStruct = RenderPassColorAttachment | dict


@dataclass(kw_only=True, repr=False)
class RenderPassDepthStencilAttachment(Struct):
    #:
    view: classes.GPUTexture | classes.GPUTextureView
    #:
    depth_clear_value: Optional[float]
    #: :obj:`enums.LoadOp <wgpu.enums.LoadOp>`
    depth_load_op: Optional[enums.LoadOpEnum]
    #: :obj:`enums.StoreOp <wgpu.enums.StoreOp>`
    depth_store_op: Optional[enums.StoreOpEnum]
    #:
    depth_read_only: Optional[bool] = False
    #:
    stencil_clear_value: Optional[int] = 0
    #: :obj:`enums.LoadOp <wgpu.enums.LoadOp>`
    stencil_load_op: Optional[enums.LoadOpEnum]
    #: :obj:`enums.StoreOp <wgpu.enums.StoreOp>`
    stencil_store_op: Optional[enums.StoreOpEnum]
    #:
    stencil_read_only: Optional[bool] = False


RenderPassDepthStencilAttachmentStruct = RenderPassDepthStencilAttachment | dict


@dataclass(kw_only=True, repr=False)
class RenderPassLayout(Struct):
    #:
    label: Optional[str] = ""
    #: list[:obj:`enums.TextureFormat <wgpu.enums.TextureFormat>`]
    color_formats: Sequence[enums.TextureFormatEnum]
    #: :obj:`enums.TextureFormat <wgpu.enums.TextureFormat>`
    depth_stencil_format: Optional[enums.TextureFormatEnum]
    #:
    sample_count: Optional[int] = 1


RenderPassLayoutStruct = RenderPassLayout | dict


@dataclass(kw_only=True, repr=False)
class RenderBundleDescriptor(Struct):
    #:
    label: Optional[str] = ""


RenderBundleDescriptorStruct = RenderBundleDescriptor | dict


@dataclass(kw_only=True, repr=False)
class RenderBundleEncoderDescriptor(Struct):
    #:
    label: Optional[str] = ""
    #: list[:obj:`enums.TextureFormat <wgpu.enums.TextureFormat>`]
    color_formats: Sequence[enums.TextureFormatEnum]
    #: :obj:`enums.TextureFormat <wgpu.enums.TextureFormat>`
    depth_stencil_format: Optional[enums.TextureFormatEnum]
    #:
    sample_count: Optional[int] = 1
    #:
    depth_read_only: Optional[bool] = False
    #:
    stencil_read_only: Optional[bool] = False


RenderBundleEncoderDescriptorStruct = RenderBundleEncoderDescriptor | dict


@dataclass(kw_only=True, repr=False)
class QueueDescriptor(Struct):
    #:
    label: Optional[str] = ""


QueueDescriptorStruct = QueueDescriptor | dict


@dataclass(kw_only=True, repr=False)
class QuerySetDescriptor(Struct):
    #:
    label: Optional[str] = ""
    #: :obj:`enums.QueryType <wgpu.enums.QueryType>`
    type: enums.QueryTypeEnum
    #:
    count: int


QuerySetDescriptorStruct = QuerySetDescriptor | dict


@dataclass(kw_only=True, repr=False)
class CanvasToneMapping(Struct):
    #: :obj:`enums.CanvasToneMappingMode <wgpu.enums.CanvasToneMappingMode>`
    mode: Optional[enums.CanvasToneMappingModeEnum] = "standard"


CanvasToneMappingStruct = CanvasToneMapping | dict


@dataclass(kw_only=True, repr=False)
class CanvasConfiguration(Struct):
    #:
    device: classes.GPUDevice
    #: :obj:`enums.TextureFormat <wgpu.enums.TextureFormat>`
    format: enums.TextureFormatEnum
    #: :obj:`flags.TextureUsage <wgpu.flags.TextureUsage>`
    usage: Optional[flags.TextureUsageFlags] = 0x10
    #: list[:obj:`enums.TextureFormat <wgpu.enums.TextureFormat>`]
    view_formats: Optional[Sequence[enums.TextureFormatEnum]] = ()
    #:
    color_space: Optional[str] = "srgb"
    #:
    tone_mapping: Optional[CanvasToneMappingStruct | None] = None
    #: :obj:`enums.CanvasAlphaMode <wgpu.enums.CanvasAlphaMode>`
    alpha_mode: Optional[enums.CanvasAlphaModeEnum] = "opaque"


CanvasConfigurationStruct = CanvasConfiguration | dict


@dataclass(kw_only=True, repr=False)
class UncapturedErrorEventInit(Struct):
    #:
    error: classes.GPUError


UncapturedErrorEventInitStruct = UncapturedErrorEventInit | dict


@dataclass(kw_only=True, repr=False)
class Color(Struct):
    #:
    r: float
    #:
    g: float
    #:
    b: float
    #:
    a: float


ColorStruct = Color | dict


@dataclass(kw_only=True, repr=False)
class Origin2D(Struct):
    #:
    x: Optional[int] = 0
    #:
    y: Optional[int] = 0


Origin2DStruct = Origin2D | dict


@dataclass(kw_only=True, repr=False)
class Origin3D(Struct):
    #:
    x: Optional[int] = 0
    #:
    y: Optional[int] = 0
    #:
    z: Optional[int] = 0


Origin3DStruct = Origin3D | dict


@dataclass(kw_only=True, repr=False)
class Extent3D(Struct):
    #:
    width: int
    #:
    height: Optional[int] = 1
    #:
    depth_or_array_layers: Optional[int] = 1


Extent3DStruct = Extent3D | dict
