// Native-only parts of Dawn's webgpu.h that the Dawn backend uses.
//
// THIS CODE IS AUTOGENERATED BY THE CODEGEN FROM wgpu/resources/dawn_webgpu.h - DO NOT EDIT
//
// The Dawn backend is compiled against Dawn's native webgpu.h, or against
// Emdawnwebgpu's webgpu.h for Pyodide. The latter lacks a few things that the
// backend uses natively (see NATIVE_ONLY in codegen/dawn_patcher.py). With
// Emscripten, this header provides them (copied from Dawn's native header), with
// functions that do nothing, so that the same _api.pyx compiles for both. The
// backend does not call these in the browser.

#ifndef WGPU_PY_DAWN_NATIVE_ONLY_H_
#define WGPU_PY_DAWN_NATIVE_ONLY_H_

#include <webgpu/webgpu.h>

#ifdef __EMSCRIPTEN__

typedef enum WGPULoggingType {
    WGPULoggingType_Verbose = 0x00000001,
    WGPULoggingType_Info = 0x00000002,
    WGPULoggingType_Warning = 0x00000003,
    WGPULoggingType_Error = 0x00000004,
    WGPULoggingType_Force32 = 0x7FFFFFFF
} WGPULoggingType WGPU_ENUM_ATTRIBUTE;

typedef void (*WGPULoggingCallback)(WGPULoggingType type, WGPUStringView message, WGPU_NULLABLE void* userdata1, WGPU_NULLABLE void* userdata2) WGPU_FUNCTION_ATTRIBUTE;

typedef struct WGPULoggingCallbackInfo {
    WGPUChainedStruct * nextInChain;
    WGPULoggingCallback callback;
    WGPU_NULLABLE void* userdata1;
    WGPU_NULLABLE void* userdata2;
} WGPULoggingCallbackInfo WGPU_STRUCTURE_ATTRIBUTE;

#define WGPU_LOGGING_CALLBACK_INFO_INIT _wgpu_MAKE_INIT_STRUCT(WGPULoggingCallbackInfo, {     /*.nextInChain=*/NULL _wgpu_COMMA     /*.callback=*/NULL _wgpu_COMMA     /*.userdata1=*/NULL _wgpu_COMMA     /*.userdata2=*/NULL _wgpu_COMMA })

typedef struct WGPUSurfaceSourceMetalLayer {
    WGPUChainedStruct chain;
    void * layer;
} WGPUSurfaceSourceMetalLayer WGPU_STRUCTURE_ATTRIBUTE;

#define WGPU_SURFACE_SOURCE_METAL_LAYER_INIT _wgpu_MAKE_INIT_STRUCT(WGPUSurfaceSourceMetalLayer, {     /*.chain=*/_wgpu_MAKE_INIT_STRUCT(WGPUChainedStruct, {         /*.next=*/NULL _wgpu_COMMA         /*.sType=*/WGPUSType_SurfaceSourceMetalLayer _wgpu_COMMA     }) _wgpu_COMMA     /*.layer=*/NULL _wgpu_COMMA })

typedef struct WGPUSurfaceSourceWaylandSurface {
    WGPUChainedStruct chain;
    void * display;
    void * surface;
} WGPUSurfaceSourceWaylandSurface WGPU_STRUCTURE_ATTRIBUTE;

#define WGPU_SURFACE_SOURCE_WAYLAND_SURFACE_INIT _wgpu_MAKE_INIT_STRUCT(WGPUSurfaceSourceWaylandSurface, {     /*.chain=*/_wgpu_MAKE_INIT_STRUCT(WGPUChainedStruct, {         /*.next=*/NULL _wgpu_COMMA         /*.sType=*/WGPUSType_SurfaceSourceWaylandSurface _wgpu_COMMA     }) _wgpu_COMMA     /*.display=*/NULL _wgpu_COMMA     /*.surface=*/NULL _wgpu_COMMA })

typedef struct WGPUSurfaceSourceWindowsHWND {
    WGPUChainedStruct chain;
    void * hinstance;
    void * hwnd;
} WGPUSurfaceSourceWindowsHWND WGPU_STRUCTURE_ATTRIBUTE;

#define WGPU_SURFACE_SOURCE_WINDOWS_HWND_INIT _wgpu_MAKE_INIT_STRUCT(WGPUSurfaceSourceWindowsHWND, {     /*.chain=*/_wgpu_MAKE_INIT_STRUCT(WGPUChainedStruct, {         /*.next=*/NULL _wgpu_COMMA         /*.sType=*/WGPUSType_SurfaceSourceWindowsHWND _wgpu_COMMA     }) _wgpu_COMMA     /*.hinstance=*/NULL _wgpu_COMMA     /*.hwnd=*/NULL _wgpu_COMMA })

typedef struct WGPUSurfaceSourceXCBWindow {
    WGPUChainedStruct chain;
    void * connection;
    uint32_t window;
} WGPUSurfaceSourceXCBWindow WGPU_STRUCTURE_ATTRIBUTE;

#define WGPU_SURFACE_SOURCE_XCB_WINDOW_INIT _wgpu_MAKE_INIT_STRUCT(WGPUSurfaceSourceXCBWindow, {     /*.chain=*/_wgpu_MAKE_INIT_STRUCT(WGPUChainedStruct, {         /*.next=*/NULL _wgpu_COMMA         /*.sType=*/WGPUSType_SurfaceSourceXCBWindow _wgpu_COMMA     }) _wgpu_COMMA     /*.connection=*/NULL _wgpu_COMMA     /*.window=*/0 _wgpu_COMMA })

typedef struct WGPUSurfaceSourceXlibWindow {
    WGPUChainedStruct chain;
    void * display;
    uint64_t window;
} WGPUSurfaceSourceXlibWindow WGPU_STRUCTURE_ATTRIBUTE;

#define WGPU_SURFACE_SOURCE_XLIB_WINDOW_INIT _wgpu_MAKE_INIT_STRUCT(WGPUSurfaceSourceXlibWindow, {     /*.chain=*/_wgpu_MAKE_INIT_STRUCT(WGPUChainedStruct, {         /*.next=*/NULL _wgpu_COMMA         /*.sType=*/WGPUSType_SurfaceSourceXlibWindow _wgpu_COMMA     }) _wgpu_COMMA     /*.display=*/NULL _wgpu_COMMA     /*.window=*/0 _wgpu_COMMA })

static inline void wgpuDeviceSetLoggingCallback(WGPUDevice device, WGPULoggingCallbackInfo callbackInfo) { (void)device; (void)callbackInfo; }

static inline void wgpuDeviceTick(WGPUDevice device) { (void)device; }

#endif  // __EMSCRIPTEN__

#endif  // WGPU_PY_DAWN_NATIVE_ONLY_H_
