"""
Codegen for the Dawn backend.

Dawn's ``webgpu.h`` (vendored as ``wgpu/resources/dawn_webgpu.h``) is the single
source of truth for the Dawn backend. From it we generate:

* ``backends/dawn/_webgpu.pxd``: the complete Cython declaration of the C API
  (handles, enums, flags, structs, callbacks, functions, constants and the
  ``WGPU_*_INIT`` struct initializers). This file is fully generated; the Cython
  compiler checks every field/function used by ``backends/dawn/_api.pyx``
  against it, and the C compiler checks it against the real header.
* ``backends/dawn/_mappings.py``: dicts to map WebGPU enum strings to the
  integer values that Dawn uses (and back).

We parse the header with pycparser (which cffi already depends on), using the
same cleaning step as for the wgpu-native headers.
"""

import re

from pycparser import c_ast, c_parser

from codegen.utils import print, format_code, to_snake_case
from codegen.hparser import get_dawn_h_parser
from codegen.idlparser import get_idl_parser
from codegen.files import file_cache, read_file


# Type names that pycparser needs to know about, but that the pxd gets from libc
STDINT_TYPES = [
    "int8_t",
    "int16_t",
    "int32_t",
    "int64_t",
    "uint8_t",
    "uint16_t",
    "uint32_t",
    "uint64_t",
    "size_t",
    "uintptr_t",
]

PXD_PREAMBLE = """
# Cython declarations of Dawn's webgpu.h, for the Dawn backend.
#
# THIS CODE IS AUTOGENERATED BY THE CODEGEN FROM wgpu/resources/dawn_webgpu.h - DO NOT EDIT

from libc.stdint cimport int8_t, int16_t, int32_t, int64_t
from libc.stdint cimport uint8_t, uint16_t, uint32_t, uint64_t, uintptr_t


cdef extern from "webgpu/webgpu.h" nogil:
""".lstrip()


def _render_type(node, name=""):
    """Render a pycparser type node as Cython-compatible C declaration."""
    if isinstance(node, c_ast.TypeDecl):
        quals = " ".join(node.quals)
        t = node.type
        if isinstance(t, c_ast.IdentifierType):
            base = " ".join(t.names)
        elif isinstance(t, (c_ast.Struct, c_ast.Enum)):
            base = t.name
        else:  # no-cover
            raise TypeError(f"Unexpected type node {t}")
        prefix = (quals + " ") if quals else ""
        return f"{prefix}{base} {name}".strip()
    elif isinstance(node, c_ast.PtrDecl):
        inner = node.type
        if isinstance(inner, c_ast.FuncDecl):
            ret = _render_type(inner.type, "")
            args = _render_args(inner.args)
            return f"{ret} (*{name})({args})"
        # Note: qualifiers on the pointer itself (e.g. "* const") are dropped.
        base = _render_type(inner, "")
        return f"{base}* {name}".strip()
    elif isinstance(node, c_ast.FuncDecl):
        ret = _render_type(node.type, "")
        args = _render_args(node.args)
        return f"{ret} {name}({args})"
    else:  # no-cover
        raise TypeError(f"Unexpected node {node}")


def _render_args(params):
    if params is None:
        return ""
    args = []
    for p in params.params:
        if isinstance(p, c_ast.Typename):  # e.g. (void)
            r = _render_type(p.type, "")
            if r == "void":
                continue
            args.append(r)
        else:
            args.append(_render_type(p.type, p.name or ""))
    return ", ".join(args)


def _tidy(s):
    s = re.sub(r"\s+", " ", s).strip()
    s = s.replace("* *", "**").replace("*  ", "* ")
    return s


def get_dawn_pxd_code():
    """Generate the Cython pxd for Dawn's webgpu.h."""

    hp = get_dawn_h_parser()
    raw_header = read_file("resources", "dawn_webgpu.h")

    # Prepare a source that pycparser can digest
    lines = []
    macros = {}
    for line in hp.source.splitlines():
        if line.startswith("#define "):
            parts = line.split()
            if len(parts) == 3:
                macros[parts[1]] = parts[2]
            continue
        if line.startswith("//"):
            continue
        lines.append(line)
    fake_typedefs = "\n".join(f"typedef int {t};" for t in STDINT_TYPES)
    source = fake_typedefs + "\n" + "\n".join(lines)
    ast = c_parser.CParser().parse(source, "dawn_webgpu.h")

    # The struct initializer macros (C compound literals) are very useful to
    # get Dawn's defaults for a struct.
    init_macros = re.findall(
        r"#define (WGPU_[A-Z0-9_]+_INIT) _wgpu_MAKE_INIT_STRUCT\((WGPU\w+),", raw_header
    )

    struct_names = []  # forward declarations
    handle_lines = []
    enum_lines = []
    flag_lines = []
    callback_lines = []
    struct_lines = []
    func_lines = []
    seen_structs = set()

    for node in ast.ext:
        if isinstance(node, c_ast.Typedef):
            name = node.name
            t = node.type
            if name in STDINT_TYPES:
                continue
            if name.startswith("WGPUProc") and name != "WGPUProc":
                continue  # The proc-table typedefs are not needed
            if isinstance(t, c_ast.TypeDecl) and isinstance(t.type, c_ast.Enum):
                enum = t.type
                enum_lines.append(f"    ctypedef enum {name}:")
                for e in enum.values.enumerators:
                    if e.name.endswith("_Force32"):
                        continue
                    enum_lines.append(f"        {e.name}")
                enum_lines.append("")
            elif isinstance(t, c_ast.TypeDecl) and isinstance(t.type, c_ast.Struct):
                struct = t.type
                if struct.decls is None:  # no-cover
                    continue
                seen_structs.add(struct.name)
                struct_lines.append(f"    cdef struct {struct.name}:")
                for decl in struct.decls:
                    struct_lines.append(
                        "        " + _tidy(_render_type(decl.type, decl.name))
                    )
                struct_lines.append("")
                if struct.name != name:  # no-cover
                    struct_lines.append(f"    ctypedef {struct.name} {name}")
            elif (
                isinstance(t, c_ast.PtrDecl)
                and isinstance(t.type, c_ast.TypeDecl)
                and isinstance(t.type.type, c_ast.Struct)
            ):
                # Opaque handle: typedef struct WGPUAdapterImpl* WGPUAdapter;
                impl = t.type.type.name
                handle_lines.append(f"    cdef struct {impl}")
                handle_lines.append(f"    ctypedef {impl}* {name}")
            elif isinstance(t, c_ast.PtrDecl) and isinstance(t.type, c_ast.FuncDecl):
                callback_lines.append(
                    "    ctypedef " + _tidy(_render_type(t, name)) + " noexcept"
                )
            elif isinstance(t, c_ast.TypeDecl) and isinstance(
                t.type, c_ast.IdentifierType
            ):
                line = f"    ctypedef {' '.join(t.type.names)} {name}"
                # WGPUFlags and WGPUBool must come before the flags
                if name in ("WGPUFlags", "WGPUBool"):
                    handle_lines.insert(0, line)
                else:
                    flag_lines.append(line)
            else:  # no-cover
                raise TypeError(f"Unexpected typedef {name}: {t}")
        elif isinstance(node, c_ast.Decl):
            t = node.type
            if isinstance(t, c_ast.FuncDecl):
                func_lines.append("    " + _tidy(_render_type(t, node.name)))
            elif isinstance(t, c_ast.Struct):
                if t.decls is None:
                    struct_names.append(t.name)  # forward declaration
                else:  # no-cover
                    raise TypeError(f"Unexpected struct declaration {t.name}")
            elif isinstance(t, c_ast.TypeDecl) and "static" in node.storage:
                # static const WGPUBufferUsage WGPUBufferUsage_MapRead = 0x01;
                flag_lines.append("    " + _tidy(_render_type(t, node.name)))
            else:  # no-cover
                raise TypeError(f"Unexpected declaration {node.name}: {t}")
        else:  # no-cover
            raise TypeError(f"Unexpected node {node}")

    # Constants from macros
    const_lines = []
    for key, val in macros.items():
        try:
            ival = int(val, 0)
        except ValueError:
            continue
        if key == "WGPU_STRLEN":
            ctype = "size_t"
        elif ival > 0xFFFFFFFF:
            ctype = "uint64_t"
        else:
            ctype = "uint32_t"
        const_lines.append(f"    const {ctype} {key}")
    const_lines.append("    const WGPUBool WGPU_TRUE")
    const_lines.append("    const WGPUBool WGPU_FALSE")

    init_lines = [f"    const {sname} {mname}" for mname, sname in init_macros]

    # Make sure that every struct has a forward declaration, so that order does not matter
    forward = [
        f"    cdef struct {name}" for name in sorted(set(struct_names) | seen_structs)
    ]

    sections = [
        ("Basic types and opaque handles", handle_lines),
        ("Constants", const_lines),
        ("Enums", enum_lines),
        ("Flags", flag_lines),
        ("Struct forward declarations", forward),
        ("Callbacks", callback_lines),
        ("Structs", struct_lines),
        ("Struct initializers (C compound literals with Dawn's defaults)", init_lines),
        ("Functions", func_lines),
    ]

    code = PXD_PREAMBLE
    for title, section_lines in sections:
        code += f"\n    # %% {title}\n\n"
        code += "\n".join(section_lines).rstrip() + "\n"

    code += "\n\n" + _get_limits_helpers(hp)

    print(
        f"Wrote _webgpu.pxd with {len(func_lines)} functions, {len(seen_structs)} structs, {len(init_lines)} initializers"
    )
    return code


def _get_limits_helpers(hp):
    """Generate inline helpers to convert WGPULimits from/to a dict."""
    fields = [key for key in hp.structs["WGPULimits"] if key != "nextInChain"]
    lines = []
    lines.append("# %% Generated helpers")
    lines.append("")
    lines.append("")
    lines.append("cdef inline dict limits_to_dict(const WGPULimits* c):")
    lines.append(
        '    """Convert a WGPULimits struct to a dict with wgpu-py limit names."""'
    )
    lines.append("    return {")
    for key in fields:
        lines.append(f'        "{to_snake_case(key, "-")}": c.{key},')
    lines.append("    }")
    lines.append("")
    lines.append("")
    lines.append("cdef inline int dict_to_limits(dict d, WGPULimits* c) except -1:")
    lines.append(
        '    """Set the fields of a WGPULimits struct from a dict with wgpu-py limit names."""'
    )
    lines.append("    cdef object v")
    for key in fields:
        lines.append(f'    v = d.get("{to_snake_case(key, "-")}")')
        lines.append("    if v is not None:")
        lines.append(f"        c.{key} = v")
    lines.append("    return 0")
    return "\n".join(lines) + "\n"


def write_dawn_pxd():
    code = get_dawn_pxd_code()
    file_cache.write("backends/dawn/_webgpu.pxd", code)


def to_dashed_name(name):
    """Convert a CamelCase name to a lowercase dashed name, keeping acronyms together.

    E.g. "SharedFenceSyncFD" -> "shared-fence-sync-fd", "D3D11MultithreadProtected"
    -> "d3d11-multithread-protected".
    """
    out = ""
    for i, c in enumerate(name):
        if i > 0 and c.isupper():
            prev = name[i - 1]
            nxt = name[i + 1] if i + 1 < len(name) else ""
            if prev.islower() or (nxt.islower() and (prev.isupper() or prev.isdigit())):
                out += "-"
        out += c.lower()
    return out


mappings_preamble = '''
""" Mappings for the Dawn backend. """

# THIS CODE IS AUTOGENERATED - DO NOT EDIT

'''.lstrip()


def compare_flags():
    """Check that the WebGPU flags have the same values in Dawn's webgpu.h."""
    idl = get_idl_parser()
    hp = get_dawn_h_parser()
    name_map = {"ColorWrite": "ColorWriteMask"}
    for name, flag in idl.flags.items():
        name = name_map.get(name, name)
        if name not in hp.flags:
            print(f"Flag {name} missing in Dawn's webgpu.h")
        else:
            for key, val in flag.items():
                key = key.title().replace("_", "")  # MAP_READ -> MapRead
                if key not in hp.flags[name]:
                    print(f"Flag field {name}.{key} missing in Dawn's webgpu.h")
                elif val != hp.flags[name][key]:
                    print(f"Warning: Flag field {name}.{key} have different values.")


def write_dawn_mappings():
    """Generate the file with dicts to map enums strings to ints for Dawn."""

    idl = get_idl_parser()
    hp = get_dawn_h_parser()

    pylines = [mappings_preamble]

    # enummap: "TextureFormat.rgba8unorm" -> int, only for the WebGPU enums
    enummap = {}
    for name in idl.enums:
        if name not in hp.enums:
            print(f"Enum {name} missing in Dawn's webgpu.h")
            continue
        hp_enum = {
            key.lower().replace("_", ""): val for key, val in hp.enums[name].items()
        }
        for ikey in idl.enums[name].values():
            hkey = ikey.lower().replace("-", "")
            if hkey in hp_enum:
                enummap[name + "." + ikey] = hp_enum[hkey]
            else:
                print(f"Enum field {name}.{ikey} missing in Dawn's webgpu.h")

    pylines.append(f"# There are {len(enummap)} enum mappings\n")
    pylines.append("enummap = {")
    for key in sorted(enummap.keys()):
        pylines.append(f'    "{key}": {enummap[key]!r},')
    pylines.append("}\n")

    # Dawn-specific mappings: key => int
    pylines.append("enum_str2int = {")
    for name, use_snake in (("BackendType", False), ("FeatureName", True)):
        pylines.append(f'    "{name}":' + " {")
        for key, val in hp.enums[name].items():
            if key == "Force32":
                continue
            if use_snake:
                key = to_dashed_name(key)
            pylines.append(f'        "{key}": {val},')
        pylines.append("    },")
    pylines.append("}")
    pylines.append("")

    # int => key, resolving to WebGPU names where possible
    pylines.append("enum_int2str = {")
    for name in [
        "BackendType",
        "AdapterType",
        "ErrorType",
        "DeviceLostReason",
        "FeatureName",
        "TextureFormat",
        "TextureDimension",
        "PresentMode",
        "CompositeAlphaMode",
        "SurfaceGetCurrentTextureStatus",
        "CompilationMessageType",
    ]:
        webgpu_names = {}
        if name in idl.enums:
            webgpu_names = {
                val.replace("-", ""): val for val in idl.enums[name].values()
            }
            if "unknown" in webgpu_names:
                webgpu_names["undefined"] = "unknown"
        pylines.append(f'    "{name}":' + " {")
        for key, val in hp.enums[name].items():
            if key == "Force32":
                continue
            if name == "FeatureName":
                enum_val = webgpu_names.get(key.lower(), to_dashed_name(key))
            else:
                enum_val = webgpu_names.get(key.lower(), key)
            pylines.append(f'        {val}: "{enum_val}",')
        pylines.append("    },")
    pylines.append("}")
    pylines.append("")

    code = format_code("\n".join(pylines))
    file_cache.write("backends/dawn/_mappings.py", code)
    print(f"Wrote {len(enummap)} enum mappings to dawn/_mappings.py")
