"""
Generate dis.py
"""

peamble = '''
"""
Python opcodes

Taken from https://github.com/beeware/batavia/blob/master/batavia/modules/dis.js
which is Copyright Russell Keith-Magee, and licensed under the 3-clause BSD.
"""

# NOTE: THIS CODE IS AUTOGENERATED; DO NOT EDIT
'''

# Read js version
js = open("dis.js", "rb").read().decode()

# Process and generate lines
pylines = []
for line in js.splitlines():
    line = line.rstrip().replace("//", "#").replace(".push(", ".append(")
    line2 = line.lstrip()
    line3 = line2.split("#")[0]
    indent = line[: len(line) - len(line2)]
    if line2.startswith(("/*", "*", "module.exports", "CO_GENERATOR:")):
        continue
    elif ": {" in line3 or ": [" in line3:
        name, _, rest = line2.partition(":")
        line = f"{indent}{name} = {rest.strip().strip(', ')}"
    elif line.startswith("var dis ="):
        line = "class dis:"
    elif line2 == "}":
        continue
    elif line.startswith("function "):
        line = line.replace("function ", "def ").replace("{", ":")
        line = line.replace(" :", ":")
    elif line.startswith("for (var op = 0; op < 256; op++)"):
        line = "for op in range(256):"
    elif line.count("+ op +"):
        line = line.replace("+ op +", "+ str(op) +")
    pylines.append(line.rstrip())

py = "\n".join(pylines).replace("\n\n\n\n", "\n\n").replace("\n\n\n", "\n\n")
py = peamble.strip() + "\n\n\n" + py.strip() + "\n"

with open("../_dis.py", "wb") as f:
    f.write(py.encode())
