"""
Build the Cython extension for the (optional) Dawn backend, in place.

The Dawn backend lives in ``wgpu/backends/dawn``. Its C-API declarations
(``_webgpu.pxd``) are generated by the codegen from Dawn's ``webgpu.h``. This
script compiles ``_api.pyx`` against Dawn's headers and links it to
``libwebgpu_dawn``. Building is optional: wgpu-py works fine without it, and
the wgpu-native backend remains the default.

Dawn is found via (in order): the ``--dawn-prefix`` argument, the
``DAWN_PREFIX`` env var, the ``CONDA_PREFIX`` env var, and ``sys.prefix``. The
prefix must contain ``include/webgpu/webgpu.h`` and the shared library in
``lib`` (``Library`` on Windows conda). Dawn can be installed from conda::

    conda install -c conda-forge dawn

On CPython >= 3.12 the extension is built against the Stable ABI (abi3), so
one binary works for all later Python versions.

Usage::

    python tools/build_dawn.py [--dawn-prefix PREFIX] [--debug]
"""

import os
import sys
import argparse
import sysconfig


ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
DAWN_DIR = os.path.join(ROOT, "wgpu", "backends", "dawn")

# Use the Stable ABI (Limited API) where Cython supports it well.
LIMITED_API_MIN = (3, 12)


def find_dawn_prefix(prefix=None):
    candidates = [
        prefix,
        os.getenv("DAWN_PREFIX"),
        os.getenv("CONDA_PREFIX"),
        sys.prefix,
    ]
    for p in candidates:
        if not p:
            continue
        for sub in ("", "Library"):
            base = os.path.join(p, sub)
            if os.path.isfile(os.path.join(base, "include", "webgpu", "webgpu.h")):
                return base
    raise RuntimeError(
        "Could not find Dawn (include/webgpu/webgpu.h). Install it with "
        "'conda install -c conda-forge dawn', or set DAWN_PREFIX."
    )


def get_extension(dawn_prefix, debug=False):
    from setuptools import Extension

    include_dir = os.path.join(dawn_prefix, "include")
    lib_dir = os.path.join(dawn_prefix, "lib")
    define_macros = []
    extra_compile_args = []
    extra_link_args = []
    py_limited_api = sys.version_info[:2] >= LIMITED_API_MIN
    if py_limited_api:
        hexversion = "0x{:02X}{:02X}0000".format(*LIMITED_API_MIN)
        define_macros.append(("Py_LIMITED_API", hexversion))
        define_macros.append(("CYTHON_LIMITED_API", "1"))

    if sys.platform.startswith("win"):
        extra_compile_args += ["/Od"] if debug else ["/O2"]
        lib_dir = os.path.join(dawn_prefix, "lib")
    else:
        extra_compile_args += ["-O0", "-g"] if debug else ["-O2"]
        # Dawn's header has a few constructs that some compilers warn about
        extra_compile_args += ["-Wno-unused-function", "-Wno-unreachable-code"]
        if sys.platform.startswith("darwin"):
            extra_link_args += [f"-Wl,-rpath,{lib_dir}"]
        else:
            extra_link_args += [f"-Wl,-rpath,{lib_dir}"]

    return Extension(
        "wgpu.backends.dawn._api",
        sources=[os.path.join(DAWN_DIR, "_api.pyx")],
        include_dirs=[include_dir],
        library_dirs=[lib_dir],
        libraries=["webgpu_dawn"],
        define_macros=define_macros,
        extra_compile_args=extra_compile_args,
        extra_link_args=extra_link_args,
        py_limited_api=py_limited_api,
    )


def build(dawn_prefix=None, debug=False):
    from Cython.Build import cythonize
    from setuptools import Distribution

    dawn_prefix = find_dawn_prefix(dawn_prefix)
    print(f"Building the Dawn backend against {dawn_prefix}")

    ext = get_extension(dawn_prefix, debug)
    ext_modules = cythonize(
        [ext],
        compiler_directives={
            "language_level": 3,
            "binding": True,
            "annotation_typing": False,
            "embedsignature": False,
            "cdivision": True,
        },
        include_path=[os.path.join(ROOT)],
        quiet=False,
    )

    options = {"build_ext": {"inplace": True}}
    if ext.py_limited_api:
        options["bdist_wheel"] = {"py_limited_api": "cp{}{}".format(*LIMITED_API_MIN)}
    dist = Distribution({"ext_modules": ext_modules, "script_name": "build_dawn.py"})
    dist.parse_config_files = lambda *a, **k: None
    for cmd, opts in options.items():
        dist.get_option_dict(cmd).update(
            {k: ("build_dawn", v) for k, v in opts.items()}
        )
    cwd = os.getcwd()
    os.chdir(ROOT)
    try:
        dist.run_command("build_ext")
    finally:
        os.chdir(cwd)

    built = [
        f
        for f in os.listdir(DAWN_DIR)
        if f.startswith("_api.") and f.endswith((".so", ".pyd"))
    ]
    print("Built:", ", ".join(built), "(stable ABI)" if ext.py_limited_api else "")
    print("Python tag:", sysconfig.get_config_var("EXT_SUFFIX"))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    parser.add_argument(
        "--dawn-prefix", default=None, help="The prefix where Dawn is installed."
    )
    parser.add_argument(
        "--debug", action="store_true", help="Build without optimizations."
    )
    args = parser.parse_args()
    build(args.dawn_prefix, args.debug)
