"""
Build the Cython extension for the (optional) Dawn backend, in place.

The Dawn backend lives in ``wgpu/backends/dawn``. Its C-API declarations
(``_webgpu.pxd``) are generated by the codegen from Dawn's ``webgpu.h``. This
script compiles ``_api.pyx`` for one of two targets:

* Native: against an installed Dawn, linking to ``libwebgpu_dawn``. Dawn is
  found via (in order): the ``--dawn-prefix`` argument, the ``DAWN_PREFIX``
  env var, the ``CONDA_PREFIX`` env var, and ``sys.prefix``. The prefix must
  contain ``include/webgpu/webgpu.h`` and the shared library in ``lib``
  (``Library`` on Windows conda). Dawn can be installed from conda::

      conda install -c conda-forge dawn

  On CPython >= 3.12 the extension is built against the Stable ABI (abi3), so
  one binary works for all later Python versions.

* Pyodide (when cross-compiling for Emscripten, e.g. with ``pyodide build``):
  against Emdawnwebgpu, Dawn's implementation of ``webgpu.h`` on top of the
  browser's WebGPU. Its C++ part is compiled into the extension, and its JS
  part is turned into ``emdawn_glue.js``, which the extension installs into
  Pyodide at import time (see ``gen_emdawn_glue.py``). The pinned Emdawnwebgpu
  release is downloaded, unless ``EMDAWNWEBGPU_PKG`` points to an extracted
  ``emdawnwebgpu_pkg`` directory. ``emcc`` must be on the PATH.

Building is optional: wgpu-py works fine without it, and the wgpu-native
backend remains the default. To include the extension in a wheel, set
``WGPU_PY_BUILD_DAWN=1`` when building the wheel (see ``hatch_build.py``).

Usage::

    python tools/build_dawn.py [--dawn-prefix PREFIX] [--debug]
"""

import io
import os
import sys
import hashlib
import argparse
import sysconfig
import subprocess
import urllib.request
import zipfile


ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
DAWN_DIR = os.path.join(ROOT, "wgpu", "backends", "dawn")
BUILD_DIR = os.path.join(ROOT, "build", "dawn")

# Use the Stable ABI (Limited API) where Cython supports it well.
LIMITED_API_MIN = (3, 12)

# The Emdawnwebgpu release for Pyodide builds. Keep this in sync with the
# vendored headers (wgpu/resources/dawn_webgpu.h and emdawn_webgpu.h), which
# are from the same Dawn release.
DAWN_TAG = "v20260929.200159"
EMDAWN_ZIP_SHA256 = "d697687e82b7377fc63f162fff0ef1cc5f025828aa4ff6ec4ac52566c949fe5f"
EMDAWN_URL = (
    f"https://github.com/google/dawn/releases/download/{DAWN_TAG}/"
    f"emdawnwebgpu_pkg-{DAWN_TAG}.zip"
)

CYTHON_DIRECTIVES = {
    "language_level": 3,
    "binding": True,
    "annotation_typing": False,
    "embedsignature": False,
    "cdivision": True,
}


def is_emscripten():
    """Whether we are (cross-)compiling for Emscripten / Pyodide."""
    plat = os.getenv("_PYTHON_HOST_PLATFORM", "") or sysconfig.get_platform()
    return plat.startswith(("emscripten", "pyodide"))


def find_dawn_prefix(prefix=None):
    candidates = [
        prefix,
        os.getenv("DAWN_PREFIX"),
        os.getenv("CONDA_PREFIX"),
        sys.prefix,
    ]
    for p in candidates:
        if not p:
            continue
        for sub in ("", "Library"):
            base = os.path.join(p, sub)
            if os.path.isfile(os.path.join(base, "include", "webgpu", "webgpu.h")):
                return base
    raise RuntimeError(
        "Could not find Dawn (include/webgpu/webgpu.h). Install it with "
        "'conda install -c conda-forge dawn', or set DAWN_PREFIX."
    )


def get_emdawnwebgpu_pkg():
    """Get the path to the (pinned) emdawnwebgpu_pkg, downloading it if needed."""
    pkg = os.getenv("EMDAWNWEBGPU_PKG")
    if pkg:
        return pkg
    pkg = os.path.join(BUILD_DIR, "emdawnwebgpu_pkg")
    if not os.path.isfile(os.path.join(pkg, "VERSION.txt")):
        print(f"Downloading {EMDAWN_URL}")
        data = urllib.request.urlopen(EMDAWN_URL).read()
        digest = hashlib.sha256(data).hexdigest()
        if digest != EMDAWN_ZIP_SHA256:
            raise RuntimeError(f"Unexpected sha256 {digest} for {EMDAWN_URL}")
        zipfile.ZipFile(io.BytesIO(data)).extractall(BUILD_DIR)
    return pkg


def get_native_extension(dawn_prefix, debug=False):
    from setuptools import Extension

    include_dir = os.path.join(dawn_prefix, "include")
    lib_dir = os.path.join(dawn_prefix, "lib")
    define_macros = []
    extra_compile_args = []
    extra_link_args = []
    py_limited_api = sys.version_info[:2] >= LIMITED_API_MIN
    if py_limited_api:
        hexversion = "0x{:02X}{:02X}0000".format(*LIMITED_API_MIN)
        define_macros.append(("Py_LIMITED_API", hexversion))
        define_macros.append(("CYTHON_LIMITED_API", "1"))

    if sys.platform.startswith("win"):
        extra_compile_args += ["/Od"] if debug else ["/O2"]
    else:
        extra_compile_args += ["-O0", "-g"] if debug else ["-O2"]
        # Dawn's header has a few constructs that some compilers warn about
        extra_compile_args += ["-Wno-unused-function", "-Wno-unreachable-code"]
        extra_link_args += [f"-Wl,-rpath,{lib_dir}"]

    ext = Extension(
        "wgpu.backends.dawn._api",
        sources=[os.path.join(DAWN_DIR, "_api.pyx")],
        include_dirs=[include_dir, DAWN_DIR],
        library_dirs=[lib_dir],
        libraries=["webgpu_dawn"],
        define_macros=define_macros,
        extra_compile_args=extra_compile_args,
        extra_link_args=extra_link_args,
        py_limited_api=py_limited_api,
    )
    ext.cpp_sources = []
    ext.cpp_args = []
    return ext


def get_emscripten_extension(debug=False):
    from setuptools import Extension

    pkg = get_emdawnwebgpu_pkg()
    gen_dir = os.path.join(BUILD_DIR, "emdawn_gen")
    os.makedirs(gen_dir, exist_ok=True)

    # Generate the JS glue (shipped next to the extension) and the list of C++
    # functions that it calls into.
    subprocess.check_call(
        [
            sys.executable,
            os.path.join(ROOT, "tools", "gen_emdawn_glue.py"),
            pkg,
            os.path.join(DAWN_DIR, "emdawn_glue.js"),
            os.path.join(gen_dir, "emdawn_cpp_funcs.h"),
            os.getenv("EMCC", "emcc"),
        ]
    )

    opt = ["-O0", "-g"] if debug else ["-O2"]
    ext = Extension(
        "wgpu.backends.dawn._api",
        sources=[os.path.join(DAWN_DIR, "_api.pyx")],
        include_dirs=[
            os.path.join(pkg, "webgpu", "include"),
            os.path.join(pkg, "webgpu", "src"),
            DAWN_DIR,
            gen_dir,
        ],
        extra_compile_args=[*opt, "-Wno-unused-function"],
    )
    # Compiled separately as C++ (see BuildExt), and linked into the extension:
    # Emdawnwebgpu's webgpu.cpp, and the code that installs the JS glue.
    ext.cpp_sources = [os.path.join(DAWN_DIR, "emdawn_glue.cpp")]
    ext.cpp_args = [*opt, "-std=c++20", "-DNDEBUG"]
    return ext


def get_build_ext_class():
    from setuptools.command.build_ext import build_ext

    class BuildExt(build_ext):
        """build_ext that can also compile C++ sources into a C extension."""

        def build_extension(self, ext):
            cpp_sources = getattr(ext, "cpp_sources", [])
            if cpp_sources:
                objects = self.compiler.compile(
                    cpp_sources,
                    output_dir=self.build_temp,
                    macros=ext.define_macros,
                    include_dirs=ext.include_dirs,
                    extra_postargs=ext.cpp_args,
                    debug=self.debug,
                )
                ext.extra_objects = list(ext.extra_objects or []) + objects
                # Link with the C++ compiler (set here, so that Cython still generates C)
                ext.language = "c++"
            super().build_extension(ext)

    return BuildExt


def build(dawn_prefix=None, debug=False):
    """Build the extension in place. Returns the paths of the built files."""
    from Cython.Build import cythonize
    from setuptools import Distribution

    if is_emscripten():
        print("Building the Dawn backend for Emscripten (Pyodide), with Emdawnwebgpu")
        ext = get_emscripten_extension(debug)
    else:
        dawn_prefix = find_dawn_prefix(dawn_prefix)
        print(f"Building the Dawn backend against {dawn_prefix}")
        ext = get_native_extension(dawn_prefix, debug)

    ext_modules = cythonize(
        [ext],
        compiler_directives=CYTHON_DIRECTIVES,
        include_path=[ROOT],
        quiet=False,
    )
    for e in ext_modules:  # cythonize() creates new Extension objects
        e.cpp_sources = ext.cpp_sources
        e.cpp_args = ext.cpp_args
        e.depends = (
            list(e.depends or [])
            + ext.cpp_sources
            + [
                os.path.join(DAWN_DIR, f)
                for f in os.listdir(DAWN_DIR)
                if f.endswith(".h")
            ]
        )

    options = {"build_ext": {"inplace": True}}
    dist = Distribution(
        {
            "ext_modules": ext_modules,
            "script_name": "build_dawn.py",
            "cmdclass": {"build_ext": get_build_ext_class()},
        }
    )
    dist.parse_config_files = lambda *a, **k: None
    for cmd, opts in options.items():
        dist.get_option_dict(cmd).update(
            {k: ("build_dawn", v) for k, v in opts.items()}
        )
    cwd = os.getcwd()
    os.chdir(ROOT)
    try:
        dist.run_command("build_ext")
    finally:
        os.chdir(cwd)

    # The built extension (the one for this target) and the files that go with it
    suffix = sysconfig.get_config_var("EXT_SUFFIX")
    if ext.py_limited_api:
        suffix = ".pyd" if sys.platform.startswith("win") else ".abi3.so"
    built = [os.path.join(DAWN_DIR, "_api" + suffix)]
    if is_emscripten():
        built.append(os.path.join(DAWN_DIR, "emdawn_glue.js"))
    for path in built:
        if not os.path.isfile(path):  # no-cover
            raise RuntimeError(f"Expected {path} to be built.")
    print("Built:", ", ".join(os.path.basename(f) for f in built))
    if ext.py_limited_api:
        print("(using the Stable ABI)")
    return built


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    parser.add_argument(
        "--dawn-prefix", default=None, help="The prefix where Dawn is installed."
    )
    parser.add_argument(
        "--debug", action="store_true", help="Build without optimizations."
    )
    args = parser.parse_args()
    build(args.dawn_prefix, args.debug)
