"""Turn Emdawnwebgpu's JS library into code that can be injected into Pyodide.

Used by tools/build_dawn.py when building the Dawn backend for Pyodide.

Emdawnwebgpu = webgpu.cpp (C++, compiled into our side module) + library_webgpu*.js
(an Emscripten JS library, which normally must be linked into the *main* module).
Pyodide extensions are side modules, which cannot carry JS libraries. So we:

1. Link a throw-away program with ``--use-port=emdawnwebgpu`` that references every
   function in webgpu.h, using the same Emscripten and the same relevant settings
   as Pyodide's main module. Emscripten's jsifier then expands all macros.
2. Cut out the "JS library code" section of the generated JS.
3. Wrap it in a function expression that takes the C++ functions it calls back
   into (emwgpuCreate*, emwgpuOn*, ...) and returns the JS functions that the
   side module imports (wgpu*, emwgpu*).

The result is evaluated at runtime (via an EM_JS function in the side module, so
it sees Pyodide's module scope: HEAPU32, _malloc, wasmImports, ...), and its
functions are put in ``wasmImports`` so that the side module's lazy import stubs
resolve to them. See wgpu/backends/dawn/emdawn_glue.cpp.

The output depends on the Emscripten version (that of Pyodide) and on the
Emdawnwebgpu release, so it is regenerated with every build.

Usage::

    python gen_emdawn_glue.py <emdawnwebgpu_pkg dir> <out.js> <out_names.h> [emcc]
"""

import os
import re
import subprocess
import sys
import tempfile


def main(pkg_dir, out_js, out_names_h, emcc="emcc"):
    port_file = os.path.join(pkg_dir, "emdawnwebgpu.port.py")
    header = os.path.join(pkg_dir, "webgpu", "include", "webgpu", "webgpu.h")
    src = open(header).read()
    funcs = sorted(
        set(
            re.findall(
                r"^WGPU_EXPORT[^;]*?\b((?:wgpu|emscripten_webgpu_)\w+)\s*\(", src, re.M
            )
        )
    )
    with tempfile.TemporaryDirectory() as tmp:
        refs_c = os.path.join(tmp, "refs.c")
        with open(refs_c, "w") as f:
            f.write("#include <webgpu/webgpu.h>\nvoid* volatile refs[] = {\n")
            for n in funcs:
                f.write(f"  (void*)&{n},\n")
            f.write("};\nint main(void) { return refs[0] == 0; }\n")
        out = os.path.join(tmp, "lib.js")
        port = f"--use-port={port_file}:cpp_bindings=false"
        subprocess.check_call([emcc, "-c", refs_c, "-o", refs_c + ".o", port])
        subprocess.check_call(
            [
                emcc[:-2] + "++",
                refs_c + ".o",
                "-o",
                out,
                port,
                "-O0",
                "-sASSERTIONS=0",
                # Match Pyodide's main module: >2GB addressing, growable memory
                "-sALLOW_MEMORY_GROWTH",
                "-sMAXIMUM_MEMORY=4GB",
                "-sERROR_ON_UNDEFINED_SYMBOLS=0",
            ]
        )
        js = open(out).read()

    lib = js.split("// Begin JS library code\n", 1)[1].split(
        "// End JS library code\n", 1
    )[0]
    lib = patch_library(lib)

    # Functions the JS calls in the wasm (implemented in webgpu.cpp)
    m = re.search(r"^var (_main, [^;]*);", js, re.M)
    wasm_exports = [s.strip() for s in m.group(1).split(",")]
    cpp_funcs = [s[1:] for s in wasm_exports if re.match(r"_(emwgpu|wgpu)\w+$", s)]

    # Functions the wasm imports from JS (implemented in library_webgpu.js)
    m = re.search(r"^var wasmImports = \{(.*?)^\};", js, re.M | re.S)
    imports = re.findall(r"(\w+): (\w+)", m.group(1))
    js_funcs = [
        (k, v)
        for k, v in imports
        if re.match(r"(emwgpu|wgpu|emscripten_webgpu_)\w+$", k)
    ]

    with open(out_js, "w") as f:
        f.write("// Generated by gen_emdawn_glue.py from Emdawnwebgpu; do not edit.\n")
        f.write("(function (cpp) {\n")
        for n in cpp_funcs:
            f.write(f"var _{n} = cpp['{n}'];\n")
        f.write(lib)
        f.write("return {\n")
        for k, v in js_funcs:
            f.write(f"  '{k}': {v},\n")
        f.write("};\n})\n")

    with open(out_names_h, "w") as f:
        f.write("// Generated by gen_emdawn_glue.py; do not edit.\n")
        f.write("#define EMDAWN_CPP_FUNCS(X) \\\n")
        f.write(" \\\n".join(f"  X({n})" for n in cpp_funcs))
        f.write("\n")
    print(f"{len(js_funcs)} JS functions, {len(cpp_funcs)} C++ callbacks -> {out_js}")


# Fixes to Emdawnwebgpu's JS code: (description, old, new)
PATCHES = [
    (
        # wgpuBufferGetMappedRange() returns a copy of the mapped range in the wasm
        # heap, which is written back on unmap. It is meant to be zero-filled, but
        # fill() is given a size instead of an end index, so it is uninitialized
        # memory. Fill it with the actual contents (like getMappedRange() in JS
        # and native Dawn), so that what is not written to is preserved.
        "GetMappedRange: initialize with the buffer contents",
        "HEAPU8.fill(0, data, mapped.byteLength);",
        "HEAPU8.set(new Uint8Array(mapped), data);",
    ),
]


def patch_library(lib):
    for description, old, new in PATCHES:
        if lib.count(old) != 1:
            raise RuntimeError(f"Cannot apply patch to Emdawnwebgpu: {description}")
        lib = lib.replace(old, new)
    return lib


if __name__ == "__main__":
    main(*sys.argv[1:])
