name: CIX

on:
  workflow_dispatch:
  push:
    branches:
      - mdic
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:

  test-builds:
    name: ${{ matrix.name }}
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Test Linux py312
            os: ubuntu-latest
            pyversion: '3.12'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.pyversion }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.pyversion }}
    - name: Install llvmpipe and lavapipe for offscreen canvas
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update -y -qq
        sudo apt install -y libegl1-mesa libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers
    - name: Install dev dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -U -r dev-requirements.txt
          python download-wgpu-native.py
          pip install -e .
    - name: Unit tests
      run: |
          pytest -v tests/test_wgpu_vertex_instance.py
          
          
